services:
  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: pdsdi
      POSTGRES_PASSWORD: pdsdi
      POSTGRES_DB: clothe_match
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./backend/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pdsdi -d clothe_match"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: l33tlsl/clothe_match_backend:latest
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1234:1234"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata:
