# [unstable]
# build-std = [
#     "--",
#     "-Z",
#     "build-std=std,panic_abort",
#     "-Z",
#     "build-std-features='optimize-for_size'",
#     "-Z",
#     "build-std-features=panic_immediate_abort",
#     "-Z",
#     "trim-paths",
# ]
